/* eslint-disable */
/* global WebImporter */
import { toTitleCase } from '../utils/text-utils.js';

/**
 * Transformer for UPS About site cleanup
 * Purpose: Remove site-wide non-content elements (header, footer, widgets, empty blocks)
 * Applies to: about.ups.com (all templates)
 * Generated: 2026-03-05
 *
 * SELECTORS EXTRACTED FROM:
 * - Captured DOM during migration of https://about.ups.com/us/en/our-impact.html
 * - cleaned.html from page scraping phase
 */

const TransformHook = {
  beforeTransform: 'beforeTransform',
  afterTransform: 'afterTransform'
};

export default function transform(hookName, element, payload) {
  if (hookName === TransformHook.beforeTransform) {
    // Remove header/navigation experience fragment
    // EXTRACTED: Found <div id="uspsr-navContainer" class="upspr-sticky-nav"> in captured DOM
    // EXTRACTED: Found <header id="upspr-headerWrap" class="pr-header navbar-header">
    WebImporter.DOMUtils.remove(element, [
      '#uspsr-navContainer',
      '.upspr-sticky-nav',
      '.cmp-experiencefragment--upspr-header-fragment'
    ]);

    // Remove footer experience fragment
    // EXTRACTED: Found <div class="cmp-experiencefragment--upspr-footer-fragment"> in captured DOM
    // EXTRACTED: Found <footer class="upspr-footer"> in captured DOM
    WebImporter.DOMUtils.remove(element, [
      '.cmp-experiencefragment--upspr-footer-fragment',
      '.upspr-footer'
    ]);

    // Remove empty content blocks (contain only &nbsp;)
    // EXTRACTED: Found <div class="pr20-contentblock"> with only empty <p>&nbsp;</p> in captured DOM
    const emptyBlocks = element.querySelectorAll('.pr20-contentblock');
    emptyBlocks.forEach((block) => {
      const text = block.textContent.trim().replace(/\u00a0/g, '');
      if (!text) {
        block.remove();
      }
    });

    // Remove dynamic media/video placeholder containers
    // EXTRACTED: Found <div class="video dynamicmedia parbase"> empty container in captured DOM
    WebImporter.DOMUtils.remove(element, [
      '.video.dynamicmedia'
    ]);

    // Remove input elements (hidden form fields used by AEM Classic)
    // EXTRACTED: Found <input id="authorModeState"> and <input id="threeColumnTeaserResource"> in captured DOM
    WebImporter.DOMUtils.remove(element, [
      'input'
    ]);

    // Remove overlay elements
    // EXTRACTED: Found <div class="upspr-overlay-global"> in captured DOM
    WebImporter.DOMUtils.remove(element, [
      '.upspr-overlay-global'
    ]);

    // Remove breadcrumb experience fragment (auto-generated by JS from URL path)
    // EXTRACTED: Found <div class="cmp-experiencefragment--breadcrumbExperienceFragment"> with
    // nested .upspr-breadcrumb-container > .upspr-breadcrumb > nav[aria-label="Breadcrumb"]
    WebImporter.DOMUtils.remove(element, [
      '.cmp-experiencefragment--breadcrumbExperienceFragment',
      '.upspr-breadcrumb-container'
    ]);

    // Remove OneTrust cookie consent SDK (banner, preference center, styles)
    // EXTRACTED: Found <div id="onetrust-consent-sdk"> and <style id="onetrust-style">
    WebImporter.DOMUtils.remove(element, [
      '#onetrust-consent-sdk',
      '#onetrust-style'
    ]);

    // Catch-all: remove any <footer> elements and their parent containers
    // Belt-and-suspenders for footer content (e.g., "This Site", "Other UPS Sites",
    // "Protect Against Fraud", copyright, "This website uses cookies...")
    WebImporter.DOMUtils.remove(element, [
      'footer'
    ]);

    // Remove tracking pixels (e.g., rlcdn.com, doubleclick, etc.)
    const trackingPixels = element.querySelectorAll('img[src*="rlcdn.com"], img[src*="doubleclick.net"], img[src*="demdex.net"]');
    trackingPixels.forEach((img) => {
      const parent = img.closest('p') || img.parentElement;
      if (parent && parent.children.length <= 1) {
        parent.remove();
      } else {
        img.remove();
      }
    });
  }

  if (hookName === TransformHook.afterTransform) {
    // Remove remaining link elements (stylesheets)
    // EXTRACTED: Found multiple <link> elements for clientlibs CSS in captured DOM
    WebImporter.DOMUtils.remove(element, [
      'link',
      'noscript'
    ]);

    // Remove decorative icons (chevrons, arrows) left behind after parsing
    // EXTRACTED: Found <i class="upspr upspr-icon-chevronright"> throughout captured DOM
    const decorativeIcons = element.querySelectorAll('i.upspr');
    decorativeIcons.forEach((icon) => {
      icon.remove();
    });

    // Remove screen reader only text spans
    // EXTRACTED: Found <span class="upspr-readerTxt"> in captured DOM
    const readerSpans = element.querySelectorAll('.upspr-readerTxt');
    readerSpans.forEach((span) => {
      span.remove();
    });

    // Convert ALL CAPS headings to Title Case (CSS handles uppercase display)
    // EXTRACTED: Found <h4>CUSTOMER FIRST, PEOPLE LED, INNOVATION DRIVEN</h4> in captured DOM
    // Rule 7: Never import all-caps content as-is
    // Only set textContent when conversion actually changes the text, to preserve
    // child elements (e.g. <a> links inside <h3>) in non-all-caps headings.
    element.querySelectorAll('h1, h2, h3, h4, h5, h6').forEach((heading) => {
      const original = heading.textContent.trim();
      const converted = toTitleCase(original);
      if (converted !== original) {
        heading.textContent = converted;
      }
    });
  }
}
